Repository tmdgusya/todo-list, pull requests merged in 2021-04, with the labels that each got.

#3 [#1] feat: :hamster: 리액트 초기설정
  FE/todolist/.gitignore
  FE/todolist/package-lock.json
  FE/todolist/package.json
  FE/todolist/public/index.html
  FE/todolist/public/robots.txt
  FE/todolist/src/App.css
  FE/todolist/src/App.js
  FE/todolist/src/App.test.js
  FE/todolist/src/index.css
  FE/todolist/src/index.js
  FE/todolist/src/reportWebVitals.js
  FE/todolist/src/setupTests.js
Labels: enhancement

#4 BackEnd 초기 설정
  BE/todoList/.gitignore
  BE/todoList/build.gradle
  BE/todoList/gradle/wrapper/gradle-wrapper.jar
  BE/todoList/gradle/wrapper/gradle-wrapper.properties
  BE/todoList/gradlew
  BE/todoList/gradlew.bat
  BE/todoList/settings.gradle
  BE/todoList/src/main/java/com/codesquad/todoList/TodoListApplication.java
  BE/todoList/src/main/java/com/codesquad/todoList/config/ApplicationConfig.java
  BE/todoList/src/main/resources/application.properties
  BE/todoList/src/test/java/com/codesquad/todoList/TodoListApplicationTests.java
Labels: enhancement

#14 [#12] feat: :hamster: Card Entity 를 생성한다.
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Card.java
  BE/todoList/src/main/resources/schema.sql
Labels: Backend, enhancement

#15 [#12] feat: :hamster: Columns Entity 를 생성한다.
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Columns.java
Labels: Backend, enhancement

#23 [#16] feat: :hamster: DDL 을 어플리케이션 실행간 자동수행
  BE/todoList/src/main/resources/application.properties
Labels: Backend, enhancement

#24 Repository 생성
  BE/todoList/src/main/java/com/codesquad/todoList/repository/ColumnRepository.java
  BE/todoList/src/main/java/com/codesquad/todoList/repository/NoteRepository.java
Labels: Backend, enhancement

#25 [#16] feat: :hamster: ColumnService 생성
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
Labels: Backend, enhancement

#26 [#16] feat: :hamster: NoteService 생성
  BE/todoList/src/main/java/com/codesquad/todoList/service/NoteService.java
Labels: Backend, enhancement

#27 [#20] feat: :hamster: ApiColumnController MockAPI 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiColumnController.java
Labels: Backend, enhancement

#28 [#21] feat: :hamster: ApiNoteController MockAPI 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiNoteController.java
Labels: Backend, enhancement

#29 [#21] feat: :hamster: ApiCardController MockAPI 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiCardController.java
Labels: Backend, enhancement

#30 [#19] feat: :hamster: NoteService 를 만든다.
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Action.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Note.java
Labels: Backend, enhancement

#32 Column Update 기능 추가 및 필요없는 코드 제거
  BE/todoList/src/main/java/com/codesquad/todoList/config/ApplicationConfig.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Card.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Columns.java
Labels: Backend, enhancement

#34 ErrorResponse 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiCardController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiColumnController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiNoteController.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Card.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Columns.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/ErrorCode.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/ErrorResponse.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/FieldError.java
Labels: Backend, enhancement

#39 Project Entity 추가 및 Mockup Api 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiProjectController.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Columns.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Project.java
  BE/todoList/src/main/java/com/codesquad/todoList/repository/ProjectRepository.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
  BE/todoList/src/main/resources/schema.sql
Labels: Backend, enhancement

#43 예외 처리 로직 생성
  BE/todoList/.gitignore
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ExceptionHandleController.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/ErrorCode.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/ErrorResponse.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/exception/NotFoundCardException.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/exception/NotFoundColumnException.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/exception/NotFoundException.java
  BE/todoList/src/main/java/com/codesquad/todoList/error/exception/NotFoundProjectException.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
  BE/todoList/src/test/java/com/codesquad/todoList/TodoListApplicationTests.java
Labels: Backend, enhancement

#45 [#44] bug: :bug: Sidebar toggle 버그해결
  FE/todolist/public/index.html
  FE/todolist/src/sidebar/Sidebar.js
Labels: Frontend, bug, style

#47 Team14/11
  FE/todolist/src/content/card/CardButton.js
  FE/todolist/src/content/card/CardInput.js
  FE/todolist/src/content/card/Form.js
Labels: Frontend, enhancement

#51 ExceptionHandler 를 통한 코드 단축
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiCardController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiColumnController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiNoteController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ExceptionHandleController.java
Labels: Backend, refactor

#52 [Sidebar] Note 데이터 요청 및 응답 완료
  .vscode/launch.json
  FE/todolist/package-lock.json
  FE/todolist/package.json
  FE/todolist/src/setUpProxy.js
  FE/todolist/src/sidebar/Sidebar.js
Labels: Frontend, enhancement

#56 CUD 작업 성공시 HttpStatus 200 리턴.
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiCardController.java
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiProjectController.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/NoteService.java
Labels: Backend, enhancement

#60 ApiCardController 생성
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
  BE/todoList/src/test/java/com/codesquad/todoList/controller/ApiCardControllerTest.java
Labels: Backend, test

#61 [Content] column 컴포넌트 생성
  FE/todolist/public/robots.txt
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/column/ColumnList.js
  FE/todolist/src/content/column/ColumnTitle.js
  FE/todolist/src/content/column/initFetchData.js
  FE/todolist/src/setUpProxy.js
Labels: Frontend, enhancement

#65 [Content] 카드 컴포넌트 생성, 스타일 작성
  FE/todolist/src/App.js
  FE/todolist/src/content/card/Card.js
  FE/todolist/src/content/card/CardInput.js
  FE/todolist/src/content/card/Form.js
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/column/ColumnTitle.js
  FE/todolist/src/utilComponent/Icon.js
Labels: Frontend, enhancement

#67 [Content] Form 컴퍼넌트 취소, 저장에 따라 리렌더링 기능 구현
  FE/todolist/src/content/card/Form.js
  FE/todolist/src/content/card/FormButton.js
  FE/todolist/src/content/card/FormInput.js
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/column/ColumnList.js
  FE/todolist/src/content/column/ColumnTitle.js
Labels: Frontend, enhancement

#70 CARD ADD 시 Response 에 CARD INFO DATA 생성
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiCardController.java
  BE/todoList/src/main/java/com/codesquad/todoList/dto/CardInfoDto.java
  BE/todoList/src/main/java/com/codesquad/todoList/entity/Columns.java
Labels: Backend, enhancement

#71 [#68] feat: :hamster: Server-Side 에서 동작에 대한 Log 를 담아준다.
  BE/todoList/src/main/java/com/codesquad/todoList/controller/ApiNoteController.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/ColumnService.java
Labels: Backend, enhancement

#72 [Content] 카드 등록 시 post 요청, sidebarLog 상태 업데이트
  FE/todolist/src/App.js
  FE/todolist/src/content/card/Card.js
  FE/todolist/src/content/card/Form.js
  FE/todolist/src/content/card/postForm.js
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/column/ColumnList.js
  FE/todolist/src/setUpProxy.js
  FE/todolist/src/utilComponent/Icon.js
Labels: Frontend, enhancement

#75 [#74] feat: :hamster: Note 최신순으로 정렬하기
  BE/todoList/src/main/java/com/codesquad/todoList/repository/NoteRepository.java
  BE/todoList/src/main/java/com/codesquad/todoList/service/NoteService.java
Labels: Backend, enhancement

#78 [Content] Card 삭제 기능 구현
  FE/todolist/src/content/card/Card.js
  FE/todolist/src/content/card/Form.js
  FE/todolist/src/content/card/postForm.js
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/column/ColumnList.js
  FE/todolist/src/content/column/initFetchData.js
  FE/todolist/src/content/httpUtils.js
  FE/todolist/src/content/util.js
Labels: Frontend, enhancement

#83 [Content] 카드 수정 기능 구현
  FE/todolist/src/content/card/Card.js
  FE/todolist/src/content/card/EditForm.js
  FE/todolist/src/content/card/Form.js
  FE/todolist/src/content/card/FormButton.js
  FE/todolist/src/content/column/Column.js
  FE/todolist/src/content/httpUtils.js
Labels: Frontend, enhancement

#84 UI 수정
  FE/todolist/src/content/card/Card.js
  FE/todolist/src/sidebar/Sidebar.js
  FE/todolist/src/sidebar/note/NoteBody.js
Labels: Frontend, enhancement, style
